# Heavily inspired from https://github.com/CheetahTemplate3/cheetah3

version: '{branch}-{build}'

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C CI\\run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python35"
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python35-x64"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python36"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python36-x64"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python37"
    - PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python37-x64"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python38"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python38-x64"
install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade pip cython pytest tox ppu"
  - "pip --version"

build_script:
  - "%WITH_ENV% python setup.py build_ext --inplace"

test_script:
  - "%CMD_IN_ENV% pytest"

deploy_script:
  # If tests are successful and we've tested a tag, deploy binary wheel
  # TWINE_USERNAME / TWINE_PASSWORD / TWINE_REPOSITORY_URL
  # must be set in AppVeyor settings.
  -  if "%APPVEYOR_REPO_TAG%" == "true" (
      pip install --upgrade twine "wheel==0.31.1" &&
      %CMD_IN_ENV% python setup.py bdist_wheel &&
      twine upload --skip-existing dist\\*.whl --repository-url %TWINE_REPOSITORY_URL% -u %TWINE_USERNAME% -p %TWINE_PASSWORD%
    )
